services:
  postgres:
    ports:
      - "5433:5432"
    image: postgres:16-alpine
    container_name: mips-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}f
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mips-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: mips-backend
    container_name: mips-backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JASYPT_PASSWORD: ${JASYPT_PASSWORD}
      OAUTH2_REDIRECT_URI: ${OAUTH2_REDIRECT_URI}
      OAUTH2_FAILED_REDIRECT_URI: ${OAUTH2_FAILED_REDIRECT_URI}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      KAKAKO_REDIRECT_URI: ${KAKAKO_REDIRECT_URI}
      PORTONE_STORE_ID: ${PORTONE_STORE_ID}
      PORTONE_SECRET: ${PORTONE_SECRET}
      PORTONE_API: ${PORTONE_API}
      PORTONE_WEBHOOK: ${PORTONE_WEBHOOK}
      KOREAEXIM_EXCHANGE_URL: ${KOREAEXIM_EXCHANGE_URL}
      KOREAEXIM_SECRET: ${KOREAEXIM_SECRET}
      COOKIE_SAME_SITE: ${COOKIE_SAME_SITE}


    networks:
      - mips-network

volumes:
  postgres_data:

networks:
  mips-network: